//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPEX_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_Fecha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIM_Fecha()
        {
            this.SOL_Presupuesto_BD = new HashSet<SOL_Presupuesto_BD>();
        }
    
        public string FechaID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string FECHA_Descripcion_corta { get; set; }
        public string FECHA_Descripcion_media { get; set; }
        public string FECHA_Descripcion_larga { get; set; }
        public Nullable<byte> DIA_Numero_Semana { get; set; }
        public byte DIA_Numero_Mes { get; set; }
        public short DIA_Numero_Anio { get; set; }
        public string DIA_Semana_Nombre { get; set; }
        public string DIA_Semana_Abrev { get; set; }
        public byte SEMANA_Numero_Anio { get; set; }
        public string SEMANA_Anio_ID { get; set; }
        public string SEMANA_Anio_Desc { get; set; }
        public byte MES_Numero { get; set; }
        public string MES_Nombre { get; set; }
        public string MES_Abrev { get; set; }
        public string MES_Anio_ID { get; set; }
        public string MES_Anio_Desc { get; set; }
        public byte TRIMESTRE_Numero { get; set; }
        public string TRIMESTRE_Nombre { get; set; }
        public string TRIMESTRE_Abrev { get; set; }
        public string TRIMESTRE_Año_ID { get; set; }
        public string ANIO2 { get; set; }
        public string ANIO4 { get; set; }
        public Nullable<System.DateTime> X_EOM_Fin_Mes { get; set; }
        public Nullable<bool> X_FinDeSemana { get; set; }
        public Nullable<bool> X_Festivo { get; set; }
        public Nullable<bool> X_AnioBisiesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_Presupuesto_BD> SOL_Presupuesto_BD { get; set; }
    }
}
