//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPEX_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOL_Presupuesto_BD
    {
        public int ID_Proyecto { get; set; }
        public System.DateTime Fecha_Pres { get; set; }
        public string PROJECT_NUMBER { get; set; }
        public Nullable<decimal> Pres_PLANIFICADO { get; set; }
        public Nullable<decimal> Pres_ORIGINAL { get; set; }
        public Nullable<decimal> Pres_MOD_44 { get; set; }
        public Nullable<decimal> Pres_ARRASTRE { get; set; }
        public string CHK { get; set; }
        public Nullable<double> Indice_VNR_ORIGEN { get; set; }
        public string FechaID { get; set; }
    
        public virtual DIM_Fecha DIM_Fecha { get; set; }
        public virtual SOL_Proyectos SOL_Proyectos { get; set; }
    }
}
