//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPEX_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOL_Centro_Costo
    {
        public int CCOSTO_ID { get; set; }
        public string CCOSTO_NOMBRE { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public Nullable<int> ACTIVADO { get; set; }
        public Nullable<int> PRINCIPAL { get; set; }
        public string GRUPO { get; set; }
        public Nullable<int> CONTABILIZA { get; set; }
        public Nullable<int> PRESUPUESTA { get; set; }
        public int CCOSTO_ACUMULACION { get; set; }
        public int AREA_ID { get; set; }
    }
}
