//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPEX_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOL_Estados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOL_Estados()
        {
            this.SOL_Proyectos = new HashSet<SOL_Proyectos>();
        }
    
        public int ESTADO_ID { get; set; }
        public string ESTADO_MODULO { get; set; }
        public string PROYECTO_STATUS { get; set; }
        public string ESTADO_PROXIMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_Proyectos> SOL_Proyectos { get; set; }
    }
}
